# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Category.create!(name: 'Seasonal')
Category.create!(name: 'Fitness')
Category.create!(name: 'Leisure')
Category.create!(name: 'Stores')
Category.create!(name: 'Wellbeing')
Category.create!(name: 'Group')
Service.create!(name: 'Football')
Service.create!(name: 'Basketball')
Service.create!(name: 'Golf')
Service.create!(name: 'Swimming')
Service.create!(name: 'Yoga')
Service.create!(name: 'Volleyball')
Service.create!(name: 'Rugby')
Service.create!(name: 'Water Polo')
Service.create!(name: 'Squash')
Service.create!(name: 'Tennis')
Service.create!(name: 'Running')
Service.create!(name: 'Horse back riding')
Service.create!(name: 'Dancing')
Service.create!(name: 'Meditation')
Tag.create!(name: 'Towels')
Tag.create!(name: 'Outdoors')
Tag.create!(name: 'Indoors')
Tag.create!(name: 'Wifi')
Tag.create!(name: 'Showers')
Tag.create!(name: 'Showers')
